In [2]:
import torch

/home/sajjad/Desktop/neural_network/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
scalar = torch.tensor(7)

vector = torch.tensor([7,8])

MATRIX = torch.tensor([[7, 4],
                       [5, 6]])

TENSOR = torch.tensor([[[1, 5, 4],
                        [1, 8, 6],
                        [5, 7, 3],
                        [8, 2, 9]],
                        [[1, 5, 4],
                        [1, 8, 6],
                        [5, 7, 3],
                        [8, 2, 9]],])

random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.5460, 0.8983, 0.9507, 0.5242],
         [0.2392, 0.0820, 0.6661, 0.9881],
         [0.9516, 0.1545, 0.7652, 0.6863]],

        [[0.5702, 0.9105, 0.5094, 0.4131],
         [0.9022, 0.1493, 0.8446, 0.9616],
         [0.7340, 0.9799, 0.8933, 0.7273]]])

In [15]:
ten = torch.arange(0, 100, 10)
zeros = torch.zeros_like(ten)
print(ten)
zeros

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
some_tensor = torch.rand(4,5)

print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"device tensor is on : {some_tensor.device}")

datatype of tensor : torch.float32
shape of tensor : torch.Size([4, 5])
device tensor is on : cpu


In [13]:
test_tensor = torch.tensor([1, 4, 8])
print({test_tensor.matmul(test_tensor)})
print({torch.matmul(test_tensor, test_tensor)})
print({test_tensor * test_tensor})
print({test_tensor + 10})

{tensor(81)}
{tensor(81)}
{tensor([ 1, 16, 64])}
{tensor([11, 14, 18])}


In [ ]:
tensor = torch.tensor([5, 8, 9, 1])
print(tensor.dtype)
print(torch.min(tensor))
print(torch.argmin(tensor))
print(torch.max(tensor))
print(torch.argmax(tensor))
print(torch.mean(tensor.type(torch.float32)))
print(torch.sum(tensor))

torch.int64
tensor(1)
tensor(3)
tensor(9)
tensor(2)
tensor(5.7500)
tensor(23)
