In [1]:
import torch
import numpy as np

In [2]:
scalar = torch.tensor(7)

vector = torch.tensor([7,8])

MATRIX = torch.tensor([[7, 4],
                       [5, 6]])

TENSOR = torch.tensor([[[1, 5, 4],
                        [1, 8, 6],
                        [5, 7, 3],
                        [8, 2, 9]],
                        [[1, 5, 4],
                        [1, 8, 6],
                        [5, 7, 3],
                        [8, 2, 9]],])

random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.9511, 0.5542, 0.2866, 0.4285],
         [0.6816, 0.9910, 0.3114, 0.3710],
         [0.2139, 0.5760, 0.4391, 0.6374]],

        [[0.5722, 0.9669, 0.9104, 0.9820],
         [0.9626, 0.9633, 0.8413, 0.6268],
         [0.6344, 0.3460, 0.1054, 0.5540]]])

In [3]:
ten = torch.arange(0, 100, 10)
zeros = torch.zeros_like(ten)
print(ten)
zeros

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
some_tensor = torch.rand(4,5)

print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"device tensor is on : {some_tensor.device}")
x = torch.arange(9).reshape(3,3)
array = x.numpy()
print(array)
z = torch.from_numpy(array)
print(z)

datatype of tensor : torch.float32
shape of tensor : torch.Size([4, 5])
device tensor is on : cpu
[[0 1 2]
 [3 4 5]
 [6 7 8]]
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [5]:
test_tensor = torch.tensor([1, 4, 8])
print({test_tensor.matmul(test_tensor)})
print({torch.matmul(test_tensor, test_tensor)})
print({test_tensor * test_tensor})
print({test_tensor + 10})

{tensor(81)}
{tensor(81)}
{tensor([ 1, 16, 64])}
{tensor([11, 14, 18])}


In [6]:
tensor = torch.tensor([5, 8, 9, 1])
print(tensor.dtype)
print(torch.min(tensor))
print(torch.argmin(tensor))
print(torch.max(tensor))
print(torch.argmax(tensor))
print(torch.mean(tensor.type(torch.float32)))
print(torch.sum(tensor))

torch.int64
tensor(1)
tensor(3)
tensor(9)
tensor(2)
tensor(5.7500)
tensor(23)


In [7]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x[0, 2, 2])
print(x[:, 2, :])
print(x[:, :, 1])

tensor(9)
tensor([[7, 8, 9]])
tensor([[2, 5, 8]])


In [8]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 5)
print(random_tensor_A)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 5)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])
